services:
  spectres-db:
    image: agnohq/pgvector:18
    container_name: spectres-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: postgres
    volumes:
      - spectres-pgdata:/var/lib/postgresql
      - ./docker/postgres/init.sh:/docker-entrypoint-initdb.d/init.sh:ro
    ports:
      - "${DB_PORT}:5432"
    networks:
      - spectres

networks:
  spectres:

volumes:
  spectres-pgdata:
